- name: Create a checkout directory variable
  set_fact:
    kreako_co_dir: "{{ ansible_user_dir }}/kreako.fr"

- name: Set a variable for logs directory
  set_fact:
    podman_logs_dir: "{{ ansible_user_dir }}/logs"

- name: Set a variable for uploads directory
  set_fact:
    uploads_dir: "{{ ansible_user_dir }}/uploads"

- name: Set a nginx directory variable to copy static files to
  set_fact:
    nginx_root_dir: "{{ ansible_user_dir }}/nginx"

- name: Set a variable for meilisearch directory storage
  set_fact:
    meilisearch_dir: "{{ ansible_user_dir }}/meilisearch"
