- name: uploads directory permissions
  ansible.builtin.file:
    path: "{{ uploads_dir }}"
    state: directory
    mode: 0777
  become: yes

- name: Remove strapi container
  containers.podman.podman_container:
    name: kreako-strapi
    image: kreako-strapi
    state: absent

- name: Create a strapi container
  containers.podman.podman_container:
    name: kreako-strapi
    image: kreako-strapi
    restart_policy: always
    pod: kreako
    volume:
      - "{{uploads_dir}}:/srv/app/public/uploads:z"
    env:
      NODE_ENV: "production"
      DATABASE_CLIENT: "postgres"
      DATABASE_HOST: "127.0.0.1"
      DATABASE_PORT: 5432
      DATABASE_NAME: "postgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "{{ postgres_password }}"
    log_opt: path={{podman_logs_dir}}/strapi.json max_size=100mb
    state: started
