FROM python:3

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN rm -rf *.py
COPY src/ .

CMD [ "uvicorn", "--host", "0.0.0.0", "--port", "1338", "main:app", "--reload" ]